import React from 'react'
// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

function NewsPage() {
  return <div>NewsPage</div>;
}

export default NewsPage